// <auto-generated />
using AmericaHospital.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmericaHospital.DAL.Migrations
{
    [DbContext(typeof(AmericaHospitalDbContext))]
    [Migration("20220602005813_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmericaHospital.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Rodrigo",
                            JobCategoryId = 0,
                            LastName = "Fuentes"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Erwin",
                            JobCategoryId = 0,
                            LastName = "Fuentes"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Pedro",
                            JobCategoryId = 0,
                            LastName = "Fuentes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
